// <auto-generated />
using System;
using HockeyPlanner.Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HockeyPlanner.Backend.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617223153_AddTeamNewsImageUrl")]
    partial class AddTeamNewsImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.AppReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("app_version");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<string>("Platform")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("platform");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Route")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("route");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_app_reports");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_app_reports_created_at");

                    b.HasIndex("Severity")
                        .HasDatabaseName("i_x_app_reports_severity");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_app_reports_status");

                    b.HasIndex("Type")
                        .HasDatabaseName("i_x_app_reports_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_app_reports_user_id");

                    b.ToTable("app_reports");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_attendances");

                    b.HasIndex("EventId")
                        .HasDatabaseName("i_x_attendances_event_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_attendances_user_id");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_attendances_event_id_user_id");

                    b.ToTable("attendances");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.EmailConfirmationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_email_confirmation_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_email_confirmation_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_email_confirmation_tokens_user_id");

                    b.ToTable("email_confirmation_tokens");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.EventGuest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<int?>("Handedness")
                        .HasColumnType("integer")
                        .HasColumnName("handedness");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("jersey_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_event_guests");

                    b.HasIndex("EventId")
                        .HasDatabaseName("i_x_event_guests_event_id");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("i_x_event_guests_invited_by_user_id");

                    b.ToTable("event_guests");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.EventTableProtocol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("TeamTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_table_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_event_table_protocols");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("i_x_event_table_protocols_created_by_user_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("i_x_event_table_protocols_event_id");

                    b.HasIndex("TeamTableId")
                        .HasDatabaseName("i_x_event_table_protocols_team_table_id");

                    b.HasIndex("EventId", "TeamTableId")
                        .IsUnique()
                        .HasDatabaseName("i_x_event_table_protocols_event_id_team_table_id");

                    b.ToTable("event_table_protocols");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.EventTableProtocolRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventTableProtocolId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_table_protocol_id");

                    b.Property<int>("Games")
                        .HasColumnType("integer")
                        .HasColumnName("games");

                    b.Property<int>("Goals")
                        .HasColumnType("integer")
                        .HasColumnName("goals");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_event_table_protocol_rows");

                    b.HasIndex("EventTableProtocolId")
                        .HasDatabaseName("i_x_event_table_protocol_rows_event_table_protocol_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_event_table_protocol_rows_user_id");

                    b.HasIndex("EventTableProtocolId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_event_table_protocol_rows_event_table_protocol_id_user_id");

                    b.ToTable("event_table_protocol_rows");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("p_k_exercises");

                    b.HasIndex("Name")
                        .HasDatabaseName("i_x_exercises_name");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("i_x_exercises_team_id");

                    b.HasIndex("TeamId", "Name")
                        .HasDatabaseName("i_x_exercises_team_id_name");

                    b.ToTable("exercises");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.GoalieApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GoalieRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("goalie_request_id");

                    b.Property<Guid>("GoalieUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("goalie_user_id");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_goalie_applications");

                    b.HasIndex("GoalieRequestId")
                        .HasDatabaseName("i_x_goalie_applications_goalie_request_id");

                    b.HasIndex("GoalieUserId")
                        .HasDatabaseName("i_x_goalie_applications_goalie_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_goalie_applications_status");

                    b.HasIndex("GoalieRequestId", "GoalieUserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_goalie_applications_goalie_request_id_goalie_user_id");

                    b.ToTable("goalie_applications");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.GoalieRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("NeededCount")
                        .HasColumnType("integer")
                        .HasColumnName("needed_count");

                    b.Property<string>("PriceText")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("price_text");

                    b.Property<int>("ResponseMode")
                        .HasColumnType("integer")
                        .HasColumnName("response_mode");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("p_k_goalie_requests");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("i_x_goalie_requests_created_by_user_id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("i_x_goalie_requests_event_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_goalie_requests_status");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("i_x_goalie_requests_team_id");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("i_x_goalie_requests_visibility");

                    b.ToTable("goalie_requests");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.InstructionArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_instruction_articles");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("i_x_instruction_articles_created_by_user_id");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("i_x_instruction_articles_is_published");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("i_x_instruction_articles_published_at");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("i_x_instruction_articles_slug");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("i_x_instruction_articles_sort_order");

                    b.ToTable("instruction_articles");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Line", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("order");

                    b.Property<Guid?>("UniformColorId")
                        .HasColumnType("uuid")
                        .HasColumnName("uniform_color_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_lines");

                    b.HasIndex("UniformColorId")
                        .HasDatabaseName("i_x_lines_uniform_color_id");

                    b.HasIndex("EventId", "Order")
                        .HasDatabaseName("i_x_lines_event_id_order");

                    b.ToTable("lines");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_notifications_user_id");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("i_x_notifications_user_id_is_read_created_at");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EndpointHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("endpoint_hash");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<Guid?>("PushSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("push_subscription_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_notification_deliveries");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_notification_deliveries_created_at");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("i_x_notification_deliveries_notification_id");

                    b.HasIndex("PushSubscriptionId")
                        .HasDatabaseName("i_x_notification_deliveries_push_subscription_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_notification_deliveries_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_notification_deliveries_user_id");

                    b.ToTable("notification_deliveries");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.NotificationPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AppUpdatesEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("app_updates_enabled");

                    b.Property<bool>("AttendanceRequiredEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("attendance_required_enabled");

                    b.Property<bool>("BirthdaysEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("birthdays_enabled");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("GoaliesEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("goalies_enabled");

                    b.Property<bool>("RosterReadyEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("roster_ready_enabled");

                    b.Property<bool>("TeamNewsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("team_news_enabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_notification_preferences");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_notification_preferences_user_id");

                    b.ToTable("notification_preferences");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_password_reset_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EventGuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_guest_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int?>("Handedness")
                        .HasColumnType("integer")
                        .HasColumnName("handedness");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("jersey_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_players");

                    b.HasIndex("EventGuestId")
                        .HasDatabaseName("i_x_players_event_guest_id");

                    b.HasIndex("LineId")
                        .HasDatabaseName("i_x_players_line_id");

                    b.HasIndex("Role")
                        .HasDatabaseName("i_x_players_role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_players_user_id");

                    b.HasIndex("LineId", "EventGuestId")
                        .IsUnique()
                        .HasDatabaseName("i_x_players_line_id_event_guest_id")
                        .HasFilter("event_guest_id IS NOT NULL");

                    b.HasIndex("LineId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_players_line_id_user_id")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("players");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("auth_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_name");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("endpoint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastBirthdayNotificationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_birthday_notification_at");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("P256dhKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("p256dh_key");

                    b.Property<string>("Platform")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("platform");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_push_subscriptions");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("i_x_push_subscriptions_endpoint");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_push_subscriptions_user_id");

                    b.ToTable("push_subscriptions");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.ReleaseNotice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("boolean")
                        .HasColumnName("notification_sent");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<bool>("SendNotification")
                        .HasColumnType("boolean")
                        .HasColumnName("send_notification");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("p_k_release_notices");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("i_x_release_notices_created_by_user_id");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("i_x_release_notices_is_published");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("i_x_release_notices_published_at");

                    b.HasIndex("Version")
                        .HasDatabaseName("i_x_release_notices_version");

                    b.ToTable("release_notices");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AwayTeamName")
                        .HasColumnType("text")
                        .HasColumnName("away_team_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("HomeTeamName")
                        .HasColumnType("text")
                        .HasColumnName("home_team_name");

                    b.Property<string>("IceRinkNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ice_rink_number");

                    b.Property<string>("LeagueName")
                        .HasColumnType("text")
                        .HasColumnName("league_name");

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location_address");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location_name");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid?>("UniformColorId")
                        .HasColumnType("uuid")
                        .HasColumnName("uniform_color_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_events");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("i_x_events_start_time");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("i_x_events_team_id");

                    b.HasIndex("UniformColorId")
                        .HasDatabaseName("i_x_events_uniform_color_id");

                    b.ToTable("events");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.ScheduledEventExercise", b =>
                {
                    b.Property<Guid>("ScheduledEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduled_event_id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("ScheduledEventId", "ExerciseId")
                        .HasName("p_k_scheduled_event_exercises");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("i_x_scheduled_event_exercises_exercise_id");

                    b.HasIndex("ScheduledEventId", "Order")
                        .HasDatabaseName("i_x_scheduled_event_exercises_scheduled_event_id_order");

                    b.ToTable("scheduled_event_exercises");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressContactsJson")
                        .HasColumnType("text")
                        .HasColumnName("address_contacts_json");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("invite_code");

                    b.Property<string>("LinkContactsJson")
                        .HasColumnType("text")
                        .HasColumnName("link_contacts_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneContactsJson")
                        .HasColumnType("text")
                        .HasColumnName("phone_contacts_json");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("p_k_teams");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("i_x_teams_invite_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("i_x_teams_name");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("i_x_teams_visibility");

                    b.HasIndex("Name", "Visibility")
                        .HasDatabaseName("i_x_teams_name_visibility");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.TeamMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BadgeTitle")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("badge_title");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_team_memberships");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("i_x_team_memberships_team_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_team_memberships_user_id");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_team_memberships_team_id_user_id");

                    b.ToTable("team_memberships");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.TeamNews", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_team_news");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("i_x_team_news_author_user_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_team_news_created_at");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("i_x_team_news_team_id");

                    b.ToTable("team_news");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.TeamTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<int>("TemplateType")
                        .HasColumnType("integer")
                        .HasColumnName("template_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_team_tables");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_team_tables_created_at");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("i_x_team_tables_created_by_user_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("i_x_team_tables_team_id");

                    b.HasIndex("TeamId", "Name")
                        .HasDatabaseName("i_x_team_tables_team_id_name");

                    b.ToTable("team_tables");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.TeamTableRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Games")
                        .HasColumnType("integer")
                        .HasColumnName("games");

                    b.Property<int>("Goals")
                        .HasColumnType("integer")
                        .HasColumnName("goals");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<Guid>("TeamTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_table_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_team_table_rows");

                    b.HasIndex("TeamTableId")
                        .HasDatabaseName("i_x_team_table_rows_team_table_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_team_table_rows_user_id");

                    b.HasIndex("TeamTableId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_team_table_rows_team_table_id_user_id");

                    b.ToTable("team_table_rows");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.UniformColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_uniform_colors");

                    b.HasIndex("Name")
                        .HasDatabaseName("i_x_uniform_colors_name");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("i_x_uniform_colors_team_id");

                    b.HasIndex("TeamId", "Name")
                        .HasDatabaseName("i_x_uniform_colors_team_id_name");

                    b.ToTable("uniform_colors");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AppRole")
                        .HasColumnType("integer")
                        .HasColumnName("app_role");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<int?>("Handedness")
                        .HasColumnType("integer")
                        .HasColumnName("handedness");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("jersey_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_updated_at");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<int?>("PrimaryPosition")
                        .HasColumnType("integer")
                        .HasColumnName("primary_position");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid?>("SpbhlPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("spbhl_player_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("AppRole")
                        .HasDatabaseName("i_x_users_app_role");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("JerseyNumber")
                        .HasDatabaseName("i_x_users_jersey_number");

                    b.HasIndex("LastName")
                        .HasDatabaseName("i_x_users_last_name");

                    b.HasIndex("Role")
                        .HasDatabaseName("i_x_users_role");

                    b.HasIndex("SpbhlPlayerId")
                        .HasDatabaseName("i_x_users_spbhl_player_id");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("i_x_users_last_name_first_name");

                    b.ToTable("users");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.AppReport", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Attendance", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", "Event")
                        .WithMany("Attendances")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.EmailConfirmationToken", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.EventGuest", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", "Event")
                        .WithMany("EventGuests")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("InvitedByUser");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.EventTableProtocol", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", "Event")
                        .WithMany("TableProtocols")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.TeamTable", "TeamTable")
                        .WithMany("Protocols")
                        .HasForeignKey("TeamTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Event");

                    b.Navigation("TeamTable");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.EventTableProtocolRow", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.EventTableProtocol", "EventTableProtocol")
                        .WithMany("Rows")
                        .HasForeignKey("EventTableProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventTableProtocol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Exercise", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.GoalieApplication", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.GoalieRequest", "GoalieRequest")
                        .WithMany("Applications")
                        .HasForeignKey("GoalieRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "GoalieUser")
                        .WithMany()
                        .HasForeignKey("GoalieUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalieRequest");

                    b.Navigation("GoalieUser");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.GoalieRequest", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", "Event")
                        .WithOne("GoalieRequest")
                        .HasForeignKey("HockeyPlanner.Backend.Core.Entities.GoalieRequest", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.Team", "Team")
                        .WithMany("GoalieRequests")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Event");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.InstructionArticle", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Line", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", "Event")
                        .WithMany("Roster")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.UniformColor", "UniformColor")
                        .WithMany()
                        .HasForeignKey("UniformColorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");

                    b.Navigation("UniformColor");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Notification", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.NotificationDelivery", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.PushSubscription", "PushSubscription")
                        .WithMany()
                        .HasForeignKey("PushSubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("PushSubscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.NotificationPreferences", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Player", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.EventGuest", "EventGuest")
                        .WithMany()
                        .HasForeignKey("EventGuestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.Line", "Line")
                        .WithMany("Players")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EventGuest");

                    b.Navigation("Line");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.PushSubscription", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.ReleaseNotice", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.Team", "Team")
                        .WithMany("Events")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.UniformColor", "UniformColor")
                        .WithMany("Events")
                        .HasForeignKey("UniformColorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");

                    b.Navigation("UniformColor");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.ScheduledEventExercise", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.Exercise", "Exercise")
                        .WithMany("ScheduledEventExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", "ScheduledEvent")
                        .WithMany("ScheduledEventExercises")
                        .HasForeignKey("ScheduledEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("ScheduledEvent");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.TeamMembership", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.Team", "Team")
                        .WithMany("Memberships")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.TeamNews", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.Team", "Team")
                        .WithMany("News")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.TeamTable", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.Team", "Team")
                        .WithMany("Tables")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.TeamTableRow", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.TeamTable", "TeamTable")
                        .WithMany("Rows")
                        .HasForeignKey("TeamTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamTable");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.UniformColor", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.EventTableProtocol", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Exercise", b =>
                {
                    b.Navigation("ScheduledEventExercises");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.GoalieRequest", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Line", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("EventGuests");

                    b.Navigation("GoalieRequest");

                    b.Navigation("Roster");

                    b.Navigation("ScheduledEventExercises");

                    b.Navigation("TableProtocols");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Team", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("GoalieRequests");

                    b.Navigation("Memberships");

                    b.Navigation("News");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.TeamTable", b =>
                {
                    b.Navigation("Protocols");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.UniformColor", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
