// <auto-generated />
using System;
using HockeyPlanner.Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HockeyPlanner.Backend.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403162259_AddUniformColorsDictionaryAndEventRelation")]
    partial class AddUniformColorsDictionaryAndEventRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_attendances");

                    b.HasIndex("EventId")
                        .HasDatabaseName("i_x_attendances_event_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_attendances_user_id");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_attendances_event_id_user_id");

                    b.ToTable("attendances");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("p_k_exercises");

                    b.HasIndex("Name")
                        .HasDatabaseName("i_x_exercises_name");

                    b.ToTable("exercises");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Line", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_lines");

                    b.HasIndex("EventId", "Order")
                        .HasDatabaseName("i_x_lines_event_id_order");

                    b.ToTable("lines");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int?>("Handedness")
                        .HasColumnType("integer")
                        .HasColumnName("handedness");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("jersey_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_players");

                    b.HasIndex("LineId")
                        .HasDatabaseName("i_x_players_line_id");

                    b.HasIndex("Role")
                        .HasDatabaseName("i_x_players_role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_players_user_id");

                    b.HasIndex("LineId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_players_line_id_user_id");

                    b.ToTable("players");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AwayTeamName")
                        .HasColumnType("text")
                        .HasColumnName("away_team_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("HomeTeamName")
                        .HasColumnType("text")
                        .HasColumnName("home_team_name");

                    b.Property<string>("IceRinkNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ice_rink_number");

                    b.Property<string>("LeagueName")
                        .HasColumnType("text")
                        .HasColumnName("league_name");

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location_address");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location_name");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid?>("UniformColorId")
                        .HasColumnType("uuid")
                        .HasColumnName("uniform_color_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_events");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("i_x_events_start_time");

                    b.HasIndex("UniformColorId")
                        .HasDatabaseName("i_x_events_uniform_color_id");

                    b.ToTable("events");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.ScheduledEventExercise", b =>
                {
                    b.Property<Guid>("ScheduledEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduled_event_id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("ScheduledEventId", "ExerciseId")
                        .HasName("p_k_scheduled_event_exercises");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("i_x_scheduled_event_exercises_exercise_id");

                    b.HasIndex("ScheduledEventId", "Order")
                        .HasDatabaseName("i_x_scheduled_event_exercises_scheduled_event_id_order");

                    b.ToTable("scheduled_event_exercises");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.UniformColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_uniform_colors");

                    b.HasIndex("Name")
                        .HasDatabaseName("i_x_uniform_colors_name");

                    b.ToTable("uniform_colors");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<int?>("Handedness")
                        .HasColumnType("integer")
                        .HasColumnName("handedness");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("jersey_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<int?>("PrimaryPosition")
                        .HasColumnType("integer")
                        .HasColumnName("primary_position");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("JerseyNumber")
                        .HasDatabaseName("i_x_users_jersey_number");

                    b.HasIndex("LastName")
                        .HasDatabaseName("i_x_users_last_name");

                    b.HasIndex("Role")
                        .HasDatabaseName("i_x_users_role");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("i_x_users_last_name_first_name");

                    b.ToTable("users");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Attendance", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", "Event")
                        .WithMany("Attendances")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Line", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", "Event")
                        .WithMany("Roster")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Player", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.Line", "Line")
                        .WithMany("Players")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.UniformColor", "UniformColor")
                        .WithMany("Events")
                        .HasForeignKey("UniformColorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UniformColor");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.ScheduledEventExercise", b =>
                {
                    b.HasOne("HockeyPlanner.Backend.Core.Entities.Exercise", "Exercise")
                        .WithMany("ScheduledEventExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", "ScheduledEvent")
                        .WithMany("ScheduledEventExercises")
                        .HasForeignKey("ScheduledEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("ScheduledEvent");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Exercise", b =>
                {
                    b.Navigation("ScheduledEventExercises");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.Line", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.ScheduledEvent", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Roster");

                    b.Navigation("ScheduledEventExercises");
                });

            modelBuilder.Entity("HockeyPlanner.Backend.Core.Entities.UniformColor", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
